### ISSUE TITLE
Ripetibilità run

### ISSUE THREAD

**Issue by stefano-dallona** [LucaVignati/plc-testbench#4]
https://github.com/LucaVignati/plc-testbench/blob/76dde393f87cd4dfded93eefc307a7d79109982c/plctestbench/plc_testbench.py#L44C11-L44C11

Ripetibilità run
============
Se due run contenenti file in comune vengono rieseguiti alternativamente, per i file comuni l'elaborazione viene rieseguita ogni volta anche se nulla è cambiato nelle rispettive configurazioni.

**Comment by LucaVignati** [comment]
Grazie, vedo se riesco a replicare e risolvere il problema.

**Comment by LucaVignati** [comment]
Sto avendo difficoltà a replicare, nello scenario che stai descrivendo cosa cambia tra i due run?
