### ISSUE TITLE
Progress_monitor cannot be overwritten

### ISSUE THREAD

**Issue by stefano-dallona** [LucaVignati/plc-testbench#5]
https://github.com/LucaVignati/plc-testbench/blob/d5c87ec8682a71c8a36389a2069a5c274677c6cd/plctestbench/plc_testbench.py#L5

With this type of import (from instead of plain old import) the progress_monitor global variabile is duplicated in the module context and cannot therefore be reassigned to customize the behaviour.

**Comment by LucaVignati** [comment]
Looks like you already have a solution, if this is the case you can go ahead and commit the change on the ui branch. I would do it but you would have to test it anyway so you can go ahead and make the changes that you need on that branch.
